version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: ./.docker/entrypoint.sh
    container_name: events-app
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '5005:5005'
    volumes:
      - .:/home/node/app
    networks:
      - 'app-network'
    depends:on:
      - db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
    ports:
      - '5435:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      - 'app-network'

networks:
  app-network:
    driver: bridge
